### ISSUE TITLE
Can't get LDAP User Manager work with azkaban 3.34

### ISSUE THREAD

**Issue by saibalpatra** [researchgate/azkaban-ldap-usermanager#14]
I have tried rebuilding this (net.researchgate.azkaban.LdapUserManager) several times and while the jar is successfully built, while authenticating against it I get the error which I does not make any sense since I am including the org.apache.directory.api jar as well.

```
_java.lang.NoSuchMethodError: org.apache.directory.api.util.Strings.toLowerCaseAscii(Ljava/lang/String;)Ljava/lang/String;
	at org.apache.directory.api.ldap.codec.api.DefaultConfigurableBinaryAttributeDetector.addBinaryAttribute(DefaultConfigurableBinaryAttributeDetector.java:166)_
```
My build.gradle file:

```
plugins {
    id 'java'
    id 'maven'
    id 'idea'
}

sourceCompatibility = 1.8

version '1.2.1-SNAPSHOT'


repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
}

configurations {
    extraLibs
}

dependencies {
    compileOnly group: 'com.github.azkaban', name: 'azkaban', version: '3.34.0'
    extraLibs group: 'org.apache.directory.api', name: 'api-all', version: '2.0.0.AM2'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile group: 'org.zapodot', name: 'embedded-ldap-junit', version: '0.5.2'
    testCompile group: 'com.github.azkaban', name: 'azkaban', version: '3.34.0'

    configurations.compile.extendsFrom(configurations.extraLibs)
}

jar {
    from {
            configurations.extraLibs.collect { it.isDirectory() ? it : zipTree(it) }
        }
}

```

**Comment by saibalpatra** [comment]
Works - I had issues with the downloaded jar files.

**Comment by jmenoud** [comment]
How did you solve it? I have the same issue and tried many version fo ldap manager, without success...
